substitutions:
  _APP_NAME: 'panel-flask-test'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_APP_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '$_APP_NAME', '--image', 'gcr.io/$PROJECT_ID/$_APP_NAME', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - 'gcr.io/$PROJECT_ID/$_APP_NAME'
